# Generated by Django 5.2.7 on 2026-08-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0004_guest_babysitting_notes_alter_group_address_line_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="song_request",
            field=models.CharField(
                blank=True,
                help_text="Un morceau qui vous ferait danser !",
                max_length=255,
                verbose_name="Une chanson pour la soirée",
            ),
        ),
    ]
