# Generated by Django 5.2.7 on 2026-08-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0005_guest_song_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="requests_sleeping",
        ),
        migrations.AddField(
            model_name="group",
            name="requests_sleeping_friday",
            field=models.BooleanField(
                default=False, verbose_name="Nuit de vendredi à samedi sur place"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="requests_sleeping_saturday",
            field=models.BooleanField(
                default=False, verbose_name="Nuit de samedi à dimanche sur place"
            ),
        ),
    ]
