# Generated by Django 5.2.7 on 2026-08-24 21:49

import wedding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0006_remove_group_requests_sleeping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="invitation_code",
            field=models.CharField(
                default=wedding.models.generate_short_code,
                editable=False,
                help_text="The unique code for their RSVP link.",
                max_length=4,
                unique=True,
            ),
        ),
    ]
