# Generated by Django 5.2.7 on 2026-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0007_alter_group_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
