# Generated by Django 5.2.7 on 2026-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0008_alter_guest_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="is_attending_brunch",
            field=models.BooleanField(
                default=False, verbose_name="Participe au Brunch"
            ),
        ),
    ]
