# Generated by Django 5.2.7 on 2025-11-01 13:56

import django.db.models.deletion
import wedding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "group_name",
                    models.CharField(
                        help_text="e.g., 'La Famille XXX' ou 'Alice & Bob'",
                        max_length=255,
                    ),
                ),
                (
                    "invitation_tier",
                    models.CharField(
                        choices=[
                            ("F", "Faire-Part uniquement"),
                            ("M", "Messe"),
                            ("K", "Cocktail"),
                            ("D", "Dinner"),
                            ("R", "Mairie"),
                        ],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        default=wedding.models.generate_short_code,
                        editable=False,
                        help_text="The unique code for their RSVP link.",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("rsvp_submitted", models.BooleanField(default=False)),
                (
                    "requests_sleeping",
                    models.BooleanField(
                        default=False, verbose_name="Requires on-site sleeping"
                    ),
                ),
                (
                    "group_message",
                    models.TextField(
                        blank=True,
                        help_text="Dietary restrictions, songs, or just a nice note!",
                        verbose_name="Message for the couple",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "is_child",
                    models.BooleanField(default=False, verbose_name="Mineure/Enfant"),
                ),
                (
                    "is_babysitted",
                    models.BooleanField(
                        default=False, verbose_name="Besoin de baby-sitting"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contact.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "is_attending_ceremony",
                    models.BooleanField(
                        default=False, verbose_name="Participe à la Cérémonie"
                    ),
                ),
                (
                    "is_attending_mairie",
                    models.BooleanField(
                        default=False, verbose_name="Participe à la Mairie"
                    ),
                ),
                (
                    "is_attending_cocktail",
                    models.BooleanField(
                        default=False, verbose_name="Participe au Cocktail"
                    ),
                ),
                (
                    "is_attending_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Participe au Dîner"
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Allergies / Régimes alimentaires",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="wedding.group",
                    ),
                ),
            ],
        ),
    ]
