# Generated by Django 5.2.7 on 2025-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="is_babysitted",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="is_child",
        ),
        migrations.AddField(
            model_name="guest",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Adresse Postale"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Enfant"),
                    ("A", "Adulte"),
                    ("B", "Enfant qui a besoin d'un baby-sitting"),
                ],
                default="A",
                max_length=1,
                verbose_name="Je suis un(e)",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_message",
            field=models.TextField(
                blank=True,
                help_text="Ce qui est important pour vous, quelque chose à prendre en compte, ou juste un petit mot!",
                verbose_name="Un message pour les mariés",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="invitation_tier",
            field=models.CharField(
                choices=[
                    ("F", "Faire-Part uniquement"),
                    ("M", "Messe (+ Faire-Part)"),
                    ("K", "Cocktail (+ Messe + Faire-Part)"),
                    ("D", "Repas (+ Cocktail + Messe + Faire-Part)"),
                    ("R", "Mairie (+ Dinner + Cocktail + Messe + Faire-Part)"),
                ],
                default="F",
                max_length=1,
            ),
        ),
    ]
