# Generated by Django 5.2.7 on 2025-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0002_remove_guest_is_babysitted_remove_guest_is_child_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="address",
        ),
        migrations.AddField(
            model_name="group",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Addresse (1)"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Addresse (Optionelle 2)"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="group",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="group",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code Postal"
            ),
        ),
    ]
