# Generated by Django 5.2.7 on 2026-08-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0003_remove_guest_address_group_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="babysitting_notes",
            field=models.TextField(
                blank=True, verbose_name="Besoins spécifiques (baby-sitting)"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Addresse (2)"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(
                help_text="e.g., 'La Famille XXX' ou 'Marine & Pierre-Antoine",
                max_length=255,
            ),
        ),
    ]
