#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the nginx web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring $app main directory..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"

myynh_fix_file_permissions

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Rebuilding Python virtualenv..."

myynh_setup_venv
myynh_fix_file_permissions

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring the systemd $app configuration..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app" --description="$app Django app"

#=================================================
# RESTORE LOGGING
#=================================================
ynh_script_progression "Restoring logging..."

myynh_setup_log_file
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# START APP
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="$log_file"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
