[project]
name = "weddjango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "gunicorn>=23.0.0",
    "img2pdf>=0.6.3",
    "pypdf>=6.16.2",
    "qrcode[pil]>=8.2",
]

[project.optional-dependencies]
dev = [
    "django-stub>=0.1",
    "django-types>=0.22.0",
]


[tool.basedpyright]
reportUninitializedInstanceVariable = false
reportUnannotatedClassAttribute = false
reportMissingTypeArgument = false
reportImplicitOverride = false
